version: 2

updates:
  - package-ecosystem: npm
    schedule:
      interval: "daily"
    directory: "/"

  - package-ecosystem: npm
    schedule:
      interval: "daily"
    directory: "docs/"

  - package-ecosystem: github-actions
    schedule:
      interval: "daily"
    directory: "/"
